# @package _global_
exp_name: ${masking.name}
seed: 0
model: wrn-22-2

masking:
  density: 0.2  # The density of the overall sparse network.
  sparse_init: erdos_renyi

  prune_rate: 0.3  # The pruning rate / prune rate.
  decay_schedule: cosine  # The decay schedule for the pruning rate. Default: cosine. Choose from: cosine, linear
  apply_when: step_end  # or step_end
  epochs: 75000 # Epochs till which mask updates are applied
  interval: 100 # Which epochs or steps to apply at
  verbose: true

dataset:
  batch_size: 128
  max_threads: 4

optimizer:
  epochs: 250
  lr: 0.1
  momentum: 0.9
  weight_decay: 5e-4
  decay_frequency: 30000
  decay_factor: 0.2