defaults:
  - masking: SNFS
  - dataset: CIFAR10
  - optimizer: SGD
  - hydra
  - hydra/job_logging: colorlog
  - hydra/hydra_logging: colorlog
  - hydra/launcher: joblib

exp_name: ${masking.name}
seed: 0
multi_seed: []
model: wrn-22-2

# Train args
device: cuda # cpu or cuda
mixed_precision: False
benchmark: False

# Logging, Saving, Resuming
log_interval: 100
ckpt_dir: ckpts
ckpt_interval: 250 #${optimizer.epochs} # Dont save any intermediate weights, just final
val_interval: 1
resume: True

# W&B
wandb:
  use: False
  api_key: ${hydra:runtime.cwd}/wandb_api.key
  entity: ml-reprod-2020
  project: cifar10
  name: ${exp_name}

wandb_api_key: ${hydra:runtime.cwd}/wandb_api.key




