defaults:
  - masking: SNFS
  - dataset: MNIST
  - optimizer: SGD
  - hydra
  - hydra/job_logging: colorlog
  - hydra/hydra_logging: colorlog
  - hydra/launcher: joblib

exp_name: ${masking.name}
seed: 0
model: lenet5

# Train args
device: cuda # cpu or cuda
mixed_precision: False
benchmark: False

# Logging, Saving, Resuming
log_interval: 100
ckpt_dir: ckpts
ckpt_interval: ${optimizer.epochs} # Dont save any intermediate weights, just final
resume: True
save_features: False

# W&B
wandb:
  use: False
  api_key: ${hydra:runtime.cwd}/wandb_api.key
  entity: ml-reprod-2020
  project: cifar10
  name: ${exp_name}

use_wandb: False
wandb_api_key: ${hydra:runtime.cwd}/wandb_api.key




