# @package _group_
name: SGD
epochs: 100

lr: 0.1 # Learning rate
momentum: 0.9 # SGD momentum

weight_decay: 5e-4 # Regularization

# LR Scheduler
decay_frequency: 25000
decay_factor: 0.1

use_nesterov: True

training_multiplier: 1 # Useful for RigL 5x etc.